"""
Django settings for InsuranceBackend project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--j7f+hc)-#itl%!w0(0^-_4uh!e3=!ezo0*@4tnyg^rr1e!rry'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*', 'https://insurance-management-abok.onrender.com']

PORT = os.environ.get('PORT', 8000)
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'app',
    'rest_framework',
    'corsheaders',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES' : ['rest_framework.permissions.AllowAny']
}
# CORS settings
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    'http://192.168.18.4:5173', 
]
APPEND_SLASH = False
ROOT_URLCONF = 'InsuranceBackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'InsuranceBackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [BASE_DIR / 'static']


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]
JAZZMIN_SETTINGS = {
    "site_title": "Insurance Admin",
    "site_header": "Insurance Dashboard",
    "welcome_sign": "Welcome to the Insurance Admin Portal",
    "custom_links": {
        "app": [  
            {
                "name": "Dashboard",
                "url": "dashboard", 
                "icon": "fas fa-chart-line", 
            },
        ],
    },
    "changeform_format": "vertical_tabs",
     "order_with_respect_to": ["auth", "dashboard", "app"],
    "topmenu_links": [
        # Add a dashboard link to the top menu
        {"name": "Dashboard", "url": "dashboard", "permissions": ["auth.view_user"]},
        {"app": "app"},  
    ],
    "copyright": "Sajha Life Insurance LTD",
    "usermenu_links": [
        # Add dashboard to the user dropdown menu
        {"name": "Dashboard", "url": "dashboard", "icon": "fas fa-home"},
    ],
    "icons": {
        # Occupation & Risk Models
        "app.occupation": "fas fa-briefcase",                      # Occupation and its risk category
        "app.mortalityrate": "fas fa-heartbeat",                   # Mortality rates

        # Company & Branch Models
        "app.company": "fas fa-building",                         # Company model
        "app.branch": "fas fa-code-branch",                       # Branches under a company

        # User and Profile Models
        "app.userprofile": "fas fa-user-circle",                  # User profile details
        "app.employee": "fas fa-user-tie",                        # Employee model
        "app.employeeposition": "fas fa-sitemap",                 # Employee positions

        # Insurance Policies
        "app.insurancepolicy": "fas fa-file-contract",            # Insurance policies
        "app.gsvrate": "fas fa-percentage",                       # Guaranteed Surrender Value rates
        "app.ssvconfig": "fas fa-cogs",                           # Special Surrender Value configurations

        # Policy Holder Models
        "app.policyholder": "fas fa-id-card",                     # Policy holder details
        "app.premiumpayment": "fas fa-wallet",                    # Premium payment records

        # Loan & Repayment
        "app.loan": "fas fa-money-check-alt",                     # Loan details
        "app.loanrepayment": "fas fa-hand-holding-usd",           # Loan repayment records

        # Sales Agents
        "app.agentapplication": "fas fa-envelope-open-text",      # Agent application form
        "app.salesagent": "fas fa-user-secret",                   # Sales agent records
        "app.agentreport": "fas fa-chart-line",                   # Agent reports

        # Bonuses & Rates
        "app.bonusrate": "fas fa-money-bill-trend-up",            # Bonus rate percentages
        "app.bonus": "fas fa-gift",                               # Bonus for policyholders

        # Claims & Processing
        "app.claimrequest": "fas fa-file-invoice-dollar",         # Claim requests
        "app.claimprocessing": "fas fa-hand-holding-dollar",      # Claim processing

        # Payment Processing
        "app.paymentprocessing": "fas fa-credit-card",            # Payment processing records

        # Underwriting
        "app.underwriting": "fas fa-shield-alt",                  # Underwriting reports and risk assessments

        # Miscellaneous
        "app.durationfactor": "fas fa-clock",                     # Duration factors for policies
    },
}
JAZZMIN_UI_TWEAKS = {
    "theme": "lumen",
    # "dark_mode_theme": "cyborg",
}